### ISSUE TITLE
Update links and layouts to harmonize with revised structure

### ISSUE THREAD

**Issue by geoffcr** [whatwg/sg#49] opened 2017-12-16 01:54 UTC
I realize that the front page of the WHATWG at https://whatwg.org/ has "history" and is not likely to change, but - to a novice user - there are some confusing elements to how the links are laid out (and some of the terminology). Here are several - some significant, some less so:

**_Workstreams_**
Where do I find a list of Workstreams? Oh - Standards; we don't call them "Workstreams" anywhere, so far as I can tell. That should presumably be fixed.
(We also might want to change the "Standards" block to say "See the other **Living** Standards developed at the WHATWG".)

**_Policies_**
Where do I find Policies? Oh - if I click on FAQ, Standards, or Participate, there's also a "Policies" tab at the top. Policies deserve a link from the main page, along with Standards and FAQ. ("Working Mode" has its own front-page button, even though it's now a subset of Policies; perhaps that should be swapped out and replaced with Policies?)

**_Signing up_**
"**Participate**" takes me to a nice narrative page, but please point people to the governing Workstream Policy and IPR Policy in addition to the Code of Conduct and the Working Mode. (This strikes me as significant.) 
"**Join**" takes me straight to the repositories instead of to the participation page. That strikes me as confusing. 

**_IRC_**
Do people still use IRC? (In other words, does it merit front-page real estate?)

_**Format**_
This is just a visual nit, but it's disorienting (to me) to fly from the "Nine Colored Blocks" front page to a "Traditional Tabbed" Standards/FAQ/Policies/Participate page, or to the Living Standards in a cleaner HTML presentation. Not sure what to fix, except perhaps to ensure that there's a consistent relationship between the tabbed pages and the front page. 

**_Review Drafts_**
Will we see the latest Review Drafts posted on the Living Standard page? For example, https://html.spec.whatwg.org/multipage/ has links to the one-page version, multipage version, developer version, translations, etc. Will there also be a "Latest Review Draft" button? (I would think so; otherwise, non-technical lawyers are going to have a hard time finding it in the repository.)

**Comment by domenic** [comment] 2017-12-16 03:29
FYI this is probably not a matter for the Steering Group, but instead something to be opened on https://github.com/whatwg/whatwg.org. Do you mind if we move the issue there?

**Comment by geoffcr** [comment] 2017-12-18 19:56
Sure - my suggestion would be for the SG to consider this, figure out what makes sense, and then move the issue over. (My raw notes aren't well-framed enough, I wouldn't think, for a copy/paste.)

**Comment by domenic** [comment] 2017-12-18 20:04
The issue is that, while the SG presumably has some final say over the website, it's mostly maintained by the community, so it's better to raise these issues in a forum where the community is paying attention. That way, we can leave whatwg/sg for specific escalations that need SG attention (e.g. if you as a community member feel the website maintainers are not being responsive and the SG needs to step in and mediate your dispute).

This is similar to how you wouldn't immediately open an issue on whatwg/sg if you had a suggested change to a living standard.

**Comment by geoffcr** [comment] 2017-12-18 20:19
Thanks. Most of these strike me as structural fixes of the kind we might have addressed as pre-Launch items if we hadn't been busy otherwise - e.g., Standards=>Workstreams, and Standards=>Living Standards, and Working Mode=>Policies; it would seem weird for me to post something in the public venue saying "Update front page to match updated terms". 

It's not the most important stuff out there, certainly, just confusing to folks who are wondering how to map the updated process to the front page. 

I'll hold on to these for now and perhaps can consider posting them later if the SG doesn't undertake to modify things.

**Comment by othermaciej** [comment] 2017-12-19 19:19
I agree with @domenic that this issue should really be in the whatwg/whatwg.org repo rather than in whatwg/sg. The SG would be happy to provide input, but I think execution and design details can be left to the existing whatwg.org website maintainers.

**Comment by othermaciej** [comment] 2017-12-21 18:02
@dbaron @henceproved @michaelchampion can you confirm that you agree with leaving these site organization changes up to the whatwg.org website maintainers (and thus we could close this issue and file a new one with same contents in whatwg/whatwg.org)?

**Comment by henceproved** [comment] 2017-12-21 18:38
Totally agree with leaving these change to the website maintainers, and moving this issue to the whatwg/whatwg.org repo.

**Comment by othermaciej** [comment] 2017-12-21 19:16
Looks like we have consensus, so moved to https://github.com/whatwg/whatwg.org/issues/149

**Closed by othermaciej** 2017-12-21 19:16 UTC
